name: Check Apache Status

on:
  workflow_call:
    inputs:
      instance_id:
        required: true
        type: string

jobs:
  check-apache:
    name: Check Apache
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: sudo apt-get install awscli -y

    - name: Get Public IP of Instance
      id: get-ip
      run: |
        ip=$(aws ec2 describe-instances --instance-ids ${{ inputs.instance_id }} --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
        echo "public_ip=$ip" >> $GITHUB_ENV

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check Apache Status
      run: |
        ssh -o "StrictHostKeyChecking=no" ec2-user@${{ env.public_ip }} "sudo systemctl is-active apache2"
      continue-on-error: false
