name: Verify Apache Installation

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed
jobs:
  verify-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: instance_ip
          path: ./terraform

      - name: Read IP Address
        id: read-ip
        run: |
          INSTANCE_IP=$(cat terraform/instance_ip.txt)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Wait for 100 seconds
        run: sleep 100

      - name: Verify Apache Installation
        run: |
          curl -I http://$INSTANCE_IP | grep "HTTP/1.1 200 OK"
