name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Save Public IP as Artifact
        working-directory: terraform
        run: |
          echo $(terraform output -raw instance_public_ip) > instance_ip.txt
        continue-on-error: true
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: instance_ip
          path: terraform/instance_ip.txt
