name: Terraform Apply

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      id: apply
      run: terraform apply -auto-approve

    - name: Save Instance ID
      run: echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_ENV

    - name: Trigger Child Workflow to Check Apache Status
      uses: goldybawa48/Apache/.github/workflows/child.yaml
      with:
        instance_id: ${{ env.instance_id }}
