name: Terraform Apply

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init

    - name: Apply Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      id: apply
      run: terraform apply -auto-approve

    - name: Save Instance ID
      run: echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_ENV

    - name: Trigger Child Workflow to Check Apache Status
      run: |
        gh workflow run child.yaml --repo goldybawa48/Apache --ref main --field instance_id="${{ env.instance_id }}"
